name: Deploy WebSocket Server

on:
  push:
    branches:
      - master  # only run when pushing to master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: avdv116/my-websocket-server:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and deploy container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          proxy_host: "185.212.60.63"
          proxy_port: "80"
          script: |
            sudo docker stop my-websocket-server || true
            sudo docker rm my-websocket-server || true
            sudo docker pull avdv116/my-websocket-server:latest
            sudo docker run -d -p 433:433 --name my-websocket-server avdv116/my-websocket-server:latest